// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuMcqCMbs2QYAM_lqmFxZR7JlV8HyHSXA',
    appId: '1:1092247496389:web:2e279153fc547cd65ff2ac',
    messagingSenderId: '1092247496389',
    projectId: 'flutter-chat-app-60e5e',
    authDomain: 'flutter-chat-app-60e5e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-60e5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxjDn8PvbNegzc6BXy9XqBuwHCMp8hgXg',
    appId: '1:1092247496389:android:066c3083400b31f25ff2ac',
    messagingSenderId: '1092247496389',
    projectId: 'flutter-chat-app-60e5e',
    storageBucket: 'flutter-chat-app-60e5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgAT4RxjeTPV7m9BcgYMqUP0l_qQewjaA',
    appId: '1:1092247496389:ios:2ba1fa9b42b5742c5ff2ac',
    messagingSenderId: '1092247496389',
    projectId: 'flutter-chat-app-60e5e',
    storageBucket: 'flutter-chat-app-60e5e.firebasestorage.app',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgAT4RxjeTPV7m9BcgYMqUP0l_qQewjaA',
    appId: '1:1092247496389:ios:2ba1fa9b42b5742c5ff2ac',
    messagingSenderId: '1092247496389',
    projectId: 'flutter-chat-app-60e5e',
    storageBucket: 'flutter-chat-app-60e5e.firebasestorage.app',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuMcqCMbs2QYAM_lqmFxZR7JlV8HyHSXA',
    appId: '1:1092247496389:web:ebe3d811c3cb6d745ff2ac',
    messagingSenderId: '1092247496389',
    projectId: 'flutter-chat-app-60e5e',
    authDomain: 'flutter-chat-app-60e5e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-60e5e.firebasestorage.app',
  );
}